### ISSUE TITLE
Paths won't work for asp.net core workflow

### ISSUE THREAD

**Issue by beforan** [UniversityOfNottingham/gulp-boilerplate#9]
The paths won't work as is, so we'd be reconfiguring per-project (but the same everytime)?

I suppose the easiest (but a faffy) way would be to leave everything as is and add a task to copy the built files to an asp.net core output path after? e.g. `wwwroot/css`

But obvs it'd be less silly to just set the output to that instead of copying afterwards.

It'd also be preferable to have a difference source path - while we can put our sass in `./src/sass` relative to the gulpfile, there will be other source outside `./src` so it seems a bit disingenuous to me.

Is there a nice way the paths can be more configurable?

**Comment by beforan** [comment]
I guess you could just expect that the const `path` is configurable per project anyway? If that's the expectation, then great.

**Comment by cooperaj** [comment]
Could always leave the moving of stuff to the CI server?

**Comment by alanshortis** [comment]
We could add a new `paths.json` file at the root and `require` it in the gulpfile rather than using an object. That way we can keep the gulpfile as is and instead define the paths we need per-project and/or have standard paths for the project type?

We could even add paths to `package.json` as that will already have project specific metadata.

**Comment by cooperaj** [comment]
I like the package.json option.

On Fri, 7 Apr 2017 at 14:48, Alan Shortis <notifications@github.com> wrote:

We could add a new paths.json file at the root and require it in the
gulpfile rather than using an object. That way we can keep the gulpfile as
is and instead define the paths we need per-project and/or have standard
paths for the project type?

We could even add paths to package.json as that will already have project
specific metadata.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/UniversityOfNottingham/gulp-boilerplate/issues/9#issuecomment-292541089>,
or mute the thread
